export const CONSTANTS = {
  vsCmdInstall: 'workbench.extensions.installExtension',
  vsCmdUninstall: 'workbench.extensions.uninstallExtension',
  cmdAddSource: 'pvmp.addSource',
  propSource: 'privateMarketplace.Source',
  propCheckUpdate: 'privateMarketplace.checkUpdate',
  propAutoUpdate: 'privateMarketplace.autoUpdate',
  propFailedUpdates: 'privateMarketplace.failedUpdates',
  cmdOpenSettings: 'pvmp.openSettings',
  cmdRefresh: 'pvmp.refresh',
  cmdView: 'pvmp.view',
  cmdUpdateBadge: 'pvmp.updateBadge',
  cmdBatchUpdate: 'pvmp.batchUpdate',
  msgSelectVersion: 'select-version',
  msgInstall: 'install',
  msgUninstall: 'uninstall',
  msgUpdate: 'update',
  cmdInstall: 'pvmp.install',
  cmdUpdate: 'pvmp.update',
  cmdUninstall: 'pvmp.uninstall',
  treeView: 'pvmp-extensions',
  extensionDetailsView: 'pvmp-extension-details',
};
